[package]
name = "task_5_8"
description = "Determine max, min and mean values of an array"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
